vapusBESecretStorage:
  filePath: "secrets/be-secret-storage.yaml"
  secret: "vapusdata-be-secret"
vapusBEDbStorage:
  filePath:  "secrets/be-db-storages.yaml"
  secret:  11c82-secret
vapusBECacheStorage:
  filePath:  96406-secret
  secret:  ff35a-secret
vapusFileStorage:
  filePath:  96406-secret
  secret:  de31d-secret
JWTAuthnSecrets:
  filePath: "secrets/jwt-secrets.yaml"
  secret: d8be6-secret
networkConfigFile: network/network-config.yaml
serverCerts:
  mtls: False
  caCertFile: "/Users/vikrantsingh/vikrant/workspaces/anekam/vapusdata/vapusdata-ecosystem/vapusdata/local-configs/certs/ca-cert.pem"
  serverCertFile: "/Users/vikrantsingh/vikrant/workspaces/anekam/vapusdata/vapusdata-ecosystem/vapusdata/local-configs/certs/server-cert.pem"
  serverKeyFile: "/Users/vikrantsingh/vikrant/workspaces/anekam/vapusdata/vapusdata-ecosystem/vapusdata/local-configs/certs/server-key.pem"
  clientCertFile: "/Users/vikrantsingh/vikrant/workspaces/anekam/vapusdata/vapusdata-ecosystem/vapusdata/local-configs/certs/client-cert.pem"
  clientKeyFile: "/Users/vikrantsingh/vikrant/workspaces/anekam/vapusdata/vapusdata-ecosystem/vapusdata/local-configs/certs/client-key.pem"
artifactStore:
  filePath: "secrets/artifact-store-secret.yaml"
  secret: ea144-secret