vapusBESecretStorage:
  filePath: "secrets/be-secret-storage.yaml"
  secret: "vapusdata-be-secret"
vapusBEDbStorage:
  filePath:  "secrets/be-db-storages.yaml"
  secret:  11c82-secret
vapusBECacheStorage:
  filePath:  96406-secret
  secret:  ff35a-secret
vapusFileStorage:
  filePath:  96406-secret
  secret:  de31d-secret
JWTAuthnSecrets:
  filePath: "secrets/jwt-secrets.yaml"
  secret: d8be6-secret
authnSecrets:
  patfilePathh: "secrets/authn-secrets.yaml"
  secret: bc7ee-secret
networkConfigFile: network/network-config.yaml
serverCerts:
  mtls: False
  caCertFile: "/Users/vikrantsingh/vikrant/workspaces/anekam/vapusdata/vapusdata-ecosystem/vapusdata/local-configs/certs/ca-cert.pem"
  serverCertFile: "/Users/vikrantsingh/vikrant/workspaces/anekam/vapusdata/vapusdata-ecosystem/vapusdata/local-configs/certs/server-cert.pem"
  serverKeyFile: "/Users/vikrantsingh/vikrant/workspaces/anekam/vapusdata/vapusdata-ecosystem/vapusdata/local-configs/certs/server-key.pem"
  clientCertFile: "/Users/vikrantsingh/vikrant/workspaces/anekam/vapusdata/vapusdata-ecosystem/vapusdata/local-configs/certs/client-cert.pem"
  clientKeyFile: "/Users/vikrantsingh/vikrant/workspaces/anekam/vapusdata/vapusdata-ecosystem/vapusdata/local-configs/certs/client-key.pem"
artifactStore:
  filePath: "secrets/artifact-store-secret.yaml"
  secret: ea144-secret
platformBaseAccount:
  platformOwners:
      - vikrant@vapusdata.com
  platformAccount:
      name: VapusData Sandbox
      creator: vikrant@vapusdata.com
  platformAccountOrganization:
      name: VapusData Sandbox Service Domain
  datamesh:
      name: VapusData DataMesh
      creator: vikrant@vapusdata.com
authnMethod: oidc
baseOs:
  - artifactType: vdc
    url: "asia-south1-docker.pkg.dev/vapusdata-beta/vapusdata-ecosystem/vapus-containers"
    digest: "sha256:68fb2f56530f752137cd2bb9b06d20eba05971960e13348f5294dd27f3901eda"
    tag: "local_vikrantsingh"
    domainMounts:
      - "/src"
  - artifactType: dataworker
    url: "asia-south1-docker.pkg.dev/vapusdata-beta/vapusdata-ecosystem/dataworker"
    digest: "sha256:9882be5e2e44b48984b793559b2ebc20a3ca64073b2f9a7807cf7b6e354c96ed"
    tag: "local_vikrantsingh"
    domainMounts:
      - "/src"