platformPolicies:
    - "vrn:vapusData:*"
domainPolicies:
    - "vrn:vapusai:*"
roles:
    - name: anonymous
      policies:
    - name: platformOwners
      policies:
    - name: platformGoverners
      policies:
    - name: domainOwners
      policies:
    - name: domainUsers
      policies:

    
