apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.nabrunners.volumePaths.serviceConfig.name }}
  labels:
    {{- include "vapusdata.nabrunners.labels" . | nindent 4 }}
data:
  nabrunners-config.yaml: |-
    vapusBESecretStorage: 
      filePath: "{{ .Values.nabrunners.volumePaths.secretsMount.path }}/{{ .Values.vapusdata.globalSecrets.backend.secretStoreFileName }}"
    vapusBEDbStorage: 
      secret:  {{ .Values.secrets.backendDataStore.secret }}
    vapusBECacheStorage: 
      secret:  {{ .Values.secrets.backendCacheStore.secret }}
    vapusFileStorage: 
      secret:  {{ .Values.secrets.fileStore.secret }}
    concurrentRunners: {{ .Values.nabrunners.concurrentRunners }}
    JWTAuthnSecrets: 
      secret: {{ .Values.secrets.JWTAuthnSecrets.secret }}
    serverCerts:
      mtls: False
      caCertFile: {{ .Values.nabrunners.volumePaths.certMount.path }}/ca-cert.pem
      serverCertFile: {{ .Values.nabrunners.volumePaths.certMount.path }}/tls.crt
      serverKeyFile: {{ .Values.nabrunners.volumePaths.certMount.path }}/tls.key
      clientCertFile: {{ .Values.nabrunners.volumePaths.certMount.path }}/client-cert.pem
      clientKeyFile: {{ .Values.nabrunners.volumePaths.certMount.path }}/client-key.pem
    artifactStore:
      secret: {{ .Values.secrets.artifactStore.secret }}
    networkConfigFile: {{ .Values.nabrunners.volumePaths.networkConfig.path }}/{{ .Values.vapusdata.globalConfigs.networkConfig.fileName }}
    trinoSpecs:
      appSelector: {{ .Values.trino.fullnameOverride }}
      namespace: {{ .Values.app.namespace }}
      trinoCordDeployment: {{ .Values.trino.coordinatorNameOverride }}
      trinoWorkerDeployment: {{ .Values.trino.workerNameOverride }}
      trinoCordSvc: {{ .Values.trino.fullnameOverride }}
      trinoWorkerSvc: {{ .Values.trino.fullnameOverride }}-worker
      trinoCordDeploymentContainer: trino-coordinator
      trinoWorkerDeploymentContainer: trino-worker
      trnioWorkerPort: {{ .Values.trino.service.port }}
      trinoCordPort: {{ .Values.trino.service.port }}
      trinoCordSvcPort: {{ .Values.trino.service.port }}
      trinoWorkerSvcPort: {{ .Values.trino.service.port }}
      trinoAppName: {{ .Values.trino.fullnameOverride }}
      trinoCatalog: {{ .Values.trino.fullnameOverride }}-catalog