apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.vapusdata.globalConfigs.policyConfig.name }}
  labels:
    {{- include "vapusdata.common.labels" . | nindent 4 }}
data:
  global-policies-config.yaml: |-
    platformPolicies:
      - "vrn:domain:ManageDomain"
      - "vrn:domain:GetDomains"
      - "vrn:domain:*"
      - "vrn:domain:GetDataCatalog"
      - "vrn:vapusData:CreateAccount"
      - "vrn:vapusData:GetAccount"
      - "vrn:vapusData:CreateDataMesh"
      - "vrn:vapusData:StoreDMSecrets"
      - "vrn:vapusData:GetDataMesh"
      - "vrn:vapusData:DiscoverMetaData"
      - "vrn:vapusData:DiscoverDataProducts"
      - "vrn:vapusData:ManageDataCatalog"
      - "vrn:vapusData:GetDataCatalog"
      - "vrn:vapusData:ConsumeDataProduct"
      - "vrn:vapusData:GetUsers"
      - "vrn:vapusData:InviteUsers"
      - "vrn:vapusData:*"
      - "vrn:vapusai:GetLLMConfiguration"
      - "vrn:vapusai:GetRagConfiguration"
      - "vrn:vapusai:GetAvailableLlms"
      - "vrn:vapusai:VapusAiInterface"
      - "vrn:vapusai:*"
    domainPolicies:
      - "vrn:domain:ManageDomain"
      - "vrn:domain:GetDomains"
      - "vrn:domain:ManageDataSource"
      - "vrn:domain:GetDataSources"
      - "vrn:domain:ManageDomainDataRules"
      - "vrn:domain:*"
      - "vrn:domain:ManageDataProducts"
      - "vrn:domain:GetDataCatalog"
      - "vrn:domain:ShareDataProducts"
      - "vrn:vapusData:GetAccount"
      - "vrn:vapusData:StoreDMSecrets"
      - "vrn:vapusData:GetDataMesh"
      - "vrn:vapusData:DiscoverMetaData"
      - "vrn:vapusData:DiscoverDataProducts"
      - "vrn:vapusData:GetDataCatalog"
      - "vrn:vapusData:ConsumeDataProduct"
      - "vrn:vapusData:GetUsers"
      - "vrn:vapusData:InviteUsers"
      - "vrn:vapusData:*"
      - "vrn:vapusai:ConfigureLlm"
      - "vrn:vapusai:ConfigureRag"
      - "vrn:vapusai:GetLLMConfiguration"
      - "vrn:vapusai:GetRagConfiguration"
      - "vrn:vapusai:GetAvailableLlms"
      - "vrn:vapusai:VapusAiInterface"
      - "vrn:vapusai:Train"
      - "vrn:vapusai:CreateEmbeddings"
      - "vrn:vapusai:RetrieveEmbeddings"
      - "vrn:vapusai:*"
    roles:
        - name: anonymous
          policies:
            - "vrn:domain:GetDomains"
            - "vrn:domain:GetDataMesh"
            - "vrn:domain:GetDataCatalog"
            - "vrn:domain:GetAvailableLlms"
        - name: platformOwners
          policies:
            - "vrn:vapusai:*"
            - "vrn:domain:*"
            - "vrn:vapusData:*"
        - name: platformAuditors
          policies:
            - "vrn:vapusData:GetAccount"
            - "vrn:vapusData:GetDataMesh"
            - "vrn:vapusData:DiscoverMetaData"
            - "vrn:vapusData:DiscoverDataProducts"
            - "vrn:vapusData:GetDataCatalog"
            - "vrn:vapusData:GetUsers"
            - "vrn:domain:GetDomains"
        - name: platformUsers
          policies:
            - "vrn:vapusData:GetAccount"
            - "vrn:vapusData:GetDataMesh"
            - "vrn:vapusData:DiscoverMetaData"
            - "vrn:vapusData:DiscoverDataProducts"
            - "vrn:vapusData:GetDataCatalog"
            - "vrn:vapusData:GetUsers"
            - "vrn:domain:GetDomains"
            - "vrn:domain:ManageDomain"       
        - name: domainOwners
          policies:
            - "vrn:vapusai:ConfigureLlm"
            - "vrn:vapusai:ConfigureRag"
            - "vrn:vapusai:GetLLMConfiguration"
            - "vrn:vapusai:GetRagConfiguration"
            - "vrn:vapusai:GetAvailableLlms"
            - "vrn:vapusai:VapusAiInterface"
            - "vrn:vapusai:Train"
            - "vrn:vapusai:CreateEmbeddings"
            - "vrn:vapusai:RetrieveEmbeddings"
            - "vrn:vapusData:GetAccount"
            - "vrn:vapusData:StoreDMSecrets"
            - "vrn:vapusData:GetDataMesh"
            - "vrn:vapusData:DiscoverMetaData"
            - "vrn:vapusData:DiscoverDataProducts"
            - "vrn:vapusData:GetDataCatalog"
            - "vrn:vapusData:ConsumeDataProduct"
            - "vrn:vapusData:GetUsers"
            - "vrn:vapusData:InviteUsers"
            - "vrn:domain:ManageDomain"
            - "vrn:domain:GetDomains"
            - "vrn:domain:ManageDataSource"
            - "vrn:domain:GetDataSources"
            - "vrn:domain:ManageDomainDataRules"
            - "vrn:domain:ManageDataProducts"
            - "vrn:domain:GetDataCatalog"
            - "vrn:domain:ShareDataProducts"
        - name: domainUsers
          policies:
            - "vrn:vapusai:GetLLMConfiguration"
            - "vrn:vapusai:GetRagConfiguration"
            - "vrn:vapusai:GetAvailableLlms"
            - "vrn:vapusai:VapusAiInterface"
            - "vrn:vapusai:Train"
            - "vrn:vapusai:CreateEmbeddings"
            - "vrn:vapusai:RetrieveEmbeddings"
            - "vrn:vapusData:GetAccount"
            - "vrn:vapusData:StoreDMSecrets"
            - "vrn:vapusData:GetDataMesh"
            - "vrn:vapusData:DiscoverMetaData"
            - "vrn:vapusData:DiscoverDataProducts"
            - "vrn:vapusData:GetDataCatalog"
            - "vrn:vapusData:ConsumeDataProduct"
            - "vrn:vapusData:GetUsers"
            - "vrn:domain:GetDomains"
            - "vrn:domain:GetDataSources"
            - "vrn:domain:ManageDataProducts"
            - "vrn:domain:GetDataCatalog"
            - "vrn:domain:ShareDataProducts"

        
  # Compare this snippet from anekam/vapusdata/vapusdata-ecosystem/vapusdata/deployments/helm-chart/vapusdata-platform/templates/configmaps/vapus-policies.yaml: