{{- if .Values.genServiceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.genServiceAccount.name }}
  namespace: {{ .Values.app.namespace}}
  labels:
    {{- include "vapusdata.common.selectorLabels" . | nindent 4 }}
  {{- with .Values.genServiceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.genServiceAccount.clusterRole.name }}
rules:
  - apiGroups: ["*"]
    resources: ["namespaces", "services","deployments","configmaps", "secrets", "pods", "pods/log", "pods/exec", "pods/portforward", "pods/proxy", "pods/status"]
    verbs: [ "get", "list"]
  - apiGroups: ["batch"]
    resources: ["cronjobs","jobs"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.genServiceAccount.clusterRoleBinding.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.genServiceAccount.clusterRole.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.genServiceAccount.name }}
    namespace: {{ .Values.app.namespace}}